apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpapi.fullname" . }}
  labels:
    {{- include "phpapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort:  {{ .Values.service.nodePort }} 
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "phpapi.selectorLabels" . | nindent 4 }}
